### ISSUE TITLE
 error: pkg-config not found

### ISSUE THREAD

**Issue by SaschaMuehl** [goodspb/pdlib#21]
Hallo @goodspb , 
I try to install the pdlib for @matiasdelellis Facerecognition app. 

During `./configure --enable-debug` I get `checking for pkg-config... configure: error: pkg-config not found`. After a search I found the config in `/usr/share/bash-completion/completions/pkg-config`. 

Could you recommend me sth. to fix the problem? (`make `and `sudo make install` isn't working without fixing, I tried)

**Comment by matiasdelellis** [comment]
Hi @SaschaMuehl 
Why not the repo???
https://github.com/matiasdelellis/facerecognition/issues/238#issuecomment-607491746

**Comment by SaschaMuehl** [comment]
Hi @matiasdelellis , 
I ran your Ubuntu Bionic Repo. But it isn't working. I aussumed a Version Shift (your Version is a 7.0, I do have 7.2). Trying with 7.2. gave me a locating error:  
```
apt install php7.2-pdlib
Reading package lists... Done
Building dependency tree
Reading state information... Done

E: Unable to locate package php7.2-pdlib
E: Couldn't find any package by glob 'php7.2-pdlib'
E: Couldn't find any package by regex 'php7.2-pdlib'
```
Therefore I tried the "hard way"

**Comment by matiasdelellis** [comment]
install php7.0-pdlib.. It is compiled against 7.2 😉

**Comment by SaschaMuehl** [comment]
Thanks @matiasdelellis, this helped. 

I didn't want to install everything lake a crazy horse:)
