### ISSUE TITLE
Release 1.0.1 ?

### ISSUE THREAD

**Issue by remicollet** [goodspb/pdlib#28]
Hi,

Tagged version 1.0 seems quite old (Aug 2018)

Is there any plan to release a bugfix 1.0.1 soon as there is lot of commits in master since.

FYI, I plan to build RPM of the library and this extension in my PHP dedicated repository, for Fedora / RHEL and CentOS, and for all PHP versions available.

https://rpms.remirepo.net/

**Comment by remicollet** [comment]
FYI:

RPM packages are now available

* **dblib-19.20** (with workaround to https://github.com/davisking/dlib/issues/2111
* **php-pdlib-1.0**-1.20200620git45c0b7 (rev 45c0b7 + PR #27 + PR #29)

Available for

*  Fedora 30, 31 and 32
* CentOS / RHEL 6, 7 and 8
- i386 and x86_64
- ZTS and TS.

**Comment by matiasdelellis** [comment]
Wow @remicollet 
Thank you for taking the lead on this. :smiley:

**Comment by goodspb** [comment]
@remicollet Thank you
