### ISSUE TITLE
How do I uninstall pdlib ? 

### ISSUE THREAD

**Issue by HeiWiper** [goodspb/pdlib#36]
I have successfully installed pdlib and now I just want to uninstall it, I tried `sudo make uninstall` but there's apparently no uninstall rule.

**Comment by xuedi** [comment]
as far as i know, there is only the modules file installed, in my case (arch linux): /usr/lib/php/modules/pdlib.so if you remove the modules, your clean again

**Comment by HeiWiper** [comment]
Alright thank you
