### ISSUE TITLE
FreeBSD -> checking for dlib-1... configure: error: dlib-1 not found

### ISSUE THREAD

**Issue by tommyatkadx** [goodspb/pdlib#41]
Hi,

I tried using:
```
pkg install dlib

New packages to be INSTALLED:
        dlib: 0.19.0
```

and also with the instruction:
```
git clone https://github.com/davisking/dlib.git
cd dlib/dlib
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON ..
make
sudo make install
```

And I always get the dlib-1 not found.

Tried to list it from pkg-config:
```
root@CiteDesNuages:/dlib/pdlib # pkg-config --list-all | grep dlib
gdlib                          gd - GD graphics library
root@CiteDesNuages:/dlib/pdlib #
```

What am I doing wrong?

**Comment by tommyatkadx** [comment]
Fixed it with:

`setenv PKG_CONFIG_PATH /usr/local/libdata/pkgconfig:/usr/libdata/pkgconfig:/usr/local/lib/pkgconfig`

**Comment by jasonhensler** [comment]
The correct port/pkg name is science/dlib-cpp (pkg install dlib-cpp). The [dlib](https://www.freshports.org/devel/dlib/) port is for "Math, XML, I/O streams, image and audio processing for D" where as [dlib-cpp](https://www.freshports.org/science/dlib-cpp/)  port is for "Machine learning framework written in C++"
