### ISSUE TITLE
make: *** [Makefile:192: pdlib.lo] Error 1

### ISSUE THREAD

**Issue by SaschaMuehl** [goodspb/pdlib#51]
Can anybody tell me what's the Error 1 means and how to solve it?

There are a lot of "error: use of deleted function". 

**First I was thinking it's because of the compiler.**

_g++ --version_
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
in the instructions are requirements for g++ 11 or higher 

So I ran `sudo apt install build-essential`
but it had already the newest version (12.8ubuntu1.1).

**Second I thought it's because of the config path**
I tried `./configure --enable-debug` and `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --enable-debug`
My dlib install location is "/root/dlib" but there is no "pkgconfig"

But the same make Error. Here is the make-log:
[putty.log](https://github.com/goodspb/pdlib/files/9666412/putty.log)

I run Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-126-generic x86_64).

**Comment by zpratikpathak** [comment]
same issue

**Comment by cyberpower678** [comment]
Same

**Comment by goodspb** [comment]
please use: https://github.com/goodspb/pdlib/releases/tag/v1.1.0
