### ISSUE TITLE
Running "make", getting ""Dlib requires C++14 support.  Give your compiler the -std=c++14 option to enable it."

### ISSUE THREAD

**Issue by sesu-san** [goodspb/pdlib#54]
I successfully went through the guide up until the part where you run "make" for the **Installation** part.

When I run make, I get:
"Dlib requires C++14 support.  Give your compiler the -std=c++14 option to enable it."
![image](https://user-images.githubusercontent.com/25572885/194627169-c317d4c3-c88e-4b4a-a194-be40db1fa009.png)

Then it just goes through a bunch of code with occasional red errors.

**Comment by Pomdre** [comment]
Solution to this in #50

**Comment by goodspb** [comment]
https://github.com/goodspb/pdlib/releases/tag/v1.1.0
