### ISSUE TITLE
Specify a license, CREDITS, and tag to an initial version.

### ISSUE THREAD

**Issue by matiasdelellis** [goodspb/pdlib#7]
Hi goodspb,
Thanks for starting the project. :smile: 

Now that is implemented the minimum we need for the nextcloud facerecognition app (when you merge the pull #6), I want to make packages fedora and debian to reduce the difficulties of access to the project.
I already have the functional fedora package for COPR, but a license is needed .. :wink: 

Regards,
Matias.

**Comment by goodspb** [comment]
Hi Matias,

Thanks for reminding me about specifying license, and also I had created an initial version. Good to have you guys contribute this project. Thanks again. :wink:

Regards,
goodspb.

**Comment by matiasdelellis** [comment]
Hi goodspb,
Thanks again... :smile: 

Remember change:
https://github.com/goodspb/pdlib/blob/master/php_pdlib.h#L34

so that phpversion ("pdlib") can reports the correct version.

Although CMake not generate any tarball, and it does not affect also change:
https://github.com/goodspb/pdlib/blob/master/CMakeLists.txt#L4
