### ISSUE TITLE
landmarks point count?

### ISSUE THREAD

**Issue by alireza1405** [goodspb/pdlib#8]
hi
first, Sorry, I do not know English;

```
$landmarks = dlib_face_landmark_detection("~/a.jpg");
var_dump($landmarks);

```
What number of landmark points does it return?
Like the image below?
[https://www.pyimagesearch.com/wp-content/uploads/2017/04/facial_landmarks_68markup.jpg](url)

**Comment by goodspb** [comment]
Like: http://dlib.net/face_landmark_detection_ex.cpp.html
